name: Third Party License Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Generate sbom json
        run: mvn cyclonedx:makeAggregateBom -f pom.xml
      - name: Build Docker image
        run:  docker build -t license_check -f ./config/Dockerfile .
      - name: Run Docker image
        run: docker run ./config -t license_check
